### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by bamorgan13** [gbarrios212/250px#2]
### Users
 - [x] Add a `likedPhotoIds` array
### Photos
 - [x] Add a `likedUserIds` array instead of `likes`
 - [x] Rename `comments` to `commentIds`
### Likes
 - [x] Remove this slice since we can incorporate the same information directly into other slices (`likedPhotoIds` on `users` and `likedUserIds` on `photos`)
### Follows
 - [x] Remove this slice for the same reasoning as `likes`

Regarding your questions, I think the suggestions above should cover them all. Likes and follows are needed as separate joins tables in our database in order to have a many-to-many relationship (`users` to `photos` and `users` to `users` respectively), but we can accomplish the same thing a little more concisely in our store by using the arrays of ids that reference the other slice directly.

Great job on the sample state! Let me know if any of the suggestions need clarification!

**Comment by gbarrios212** [comment]
Thank you Bryce.  This makes a lot of sense!
