### ISSUE TITLE
Frontend Routes

### ISSUE THREAD

**Issue by bamorgan13** [gbarrios212/250px#4]
### Username
 - [x] Having a wildcard refer to a `username` instead of an `id` can be a little bit trickier than what we've done recently. In order to key in to the correct slice of state you would have to know how those two relate, meaning you would have to implement a fetch by `username` and map the `username` to the corresponding `id`. It's completely doable, just something that's not an immediately obvious task. I'm completely fine with you doing it this way or doing a typical `/users/:id`.
### Gallery
 - [x] Same idea as above, I'm okay with you using the `:id` instead of the `gallery's` `name` in the route

 Good work! I think you have a great foundation! Let me know if the name vs. id situation doesn't make sense.

**Comment by gbarrios212** [comment]
Thank you Bryce!  Switching those over now!
